# CMake generated Testfile for 
# Source directory: /home/zzp/code/NoPFS/pytorch/caffe2
# Build directory: /home/zzp/code/NoPFS/pytorch/build/caffe2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vec_test_all_types_DEFAULT "/home/zzp/code/NoPFS/pytorch/build/bin/vec_test_all_types_DEFAULT")
add_test(vec_test_all_types_AVX2 "/home/zzp/code/NoPFS/pytorch/build/bin/vec_test_all_types_AVX2")
add_test(scalar_test "/home/zzp/code/NoPFS/pytorch/build/bin/scalar_test")
add_test(apply_utils_test "/home/zzp/code/NoPFS/pytorch/build/bin/apply_utils_test")
add_test(basic "/home/zzp/code/NoPFS/pytorch/build/bin/basic")
add_test(atest "/home/zzp/code/NoPFS/pytorch/build/bin/atest")
add_test(Dimname_test "/home/zzp/code/NoPFS/pytorch/build/bin/Dimname_test")
add_test(Dict_test "/home/zzp/code/NoPFS/pytorch/build/bin/Dict_test")
add_test(NamedTensor_test "/home/zzp/code/NoPFS/pytorch/build/bin/NamedTensor_test")
add_test(half_test "/home/zzp/code/NoPFS/pytorch/build/bin/half_test")
add_test(broadcast_test "/home/zzp/code/NoPFS/pytorch/build/bin/broadcast_test")
add_test(wrapdim_test "/home/zzp/code/NoPFS/pytorch/build/bin/wrapdim_test")
add_test(dlconvertor_test "/home/zzp/code/NoPFS/pytorch/build/bin/dlconvertor_test")
add_test(native_test "/home/zzp/code/NoPFS/pytorch/build/bin/native_test")
add_test(scalar_tensor_test "/home/zzp/code/NoPFS/pytorch/build/bin/scalar_tensor_test")
add_test(test_parallel "/home/zzp/code/NoPFS/pytorch/build/bin/test_parallel")
add_test(undefined_tensor_test "/home/zzp/code/NoPFS/pytorch/build/bin/undefined_tensor_test")
add_test(verify_api_visibility "/home/zzp/code/NoPFS/pytorch/build/bin/verify_api_visibility")
add_test(thread_init_test "/home/zzp/code/NoPFS/pytorch/build/bin/thread_init_test")
add_test(weakref_test "/home/zzp/code/NoPFS/pytorch/build/bin/weakref_test")
add_test(quantized_test "/home/zzp/code/NoPFS/pytorch/build/bin/quantized_test")
add_test(extension_backend_test "/home/zzp/code/NoPFS/pytorch/build/bin/extension_backend_test")
add_test(operators_test "/home/zzp/code/NoPFS/pytorch/build/bin/operators_test")
add_test(lazy_tensor_test "/home/zzp/code/NoPFS/pytorch/build/bin/lazy_tensor_test")
add_test(tensor_iterator_test "/home/zzp/code/NoPFS/pytorch/build/bin/tensor_iterator_test")
add_test(math_kernel_test "/home/zzp/code/NoPFS/pytorch/build/bin/math_kernel_test")
add_test(memory_overlapping_test "/home/zzp/code/NoPFS/pytorch/build/bin/memory_overlapping_test")
add_test(mobile_memory_cleanup "/home/zzp/code/NoPFS/pytorch/build/bin/mobile_memory_cleanup")
add_test(cpu_generator_test "/home/zzp/code/NoPFS/pytorch/build/bin/cpu_generator_test")
add_test(cpu_profiling_allocator_test "/home/zzp/code/NoPFS/pytorch/build/bin/cpu_profiling_allocator_test")
add_test(pow_test "/home/zzp/code/NoPFS/pytorch/build/bin/pow_test")
add_test(variant_test "/home/zzp/code/NoPFS/pytorch/build/bin/variant_test")
add_test(reduce_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/reduce_ops_test")
add_test(reportMemoryUsage_test "/home/zzp/code/NoPFS/pytorch/build/bin/reportMemoryUsage_test")
add_test(memory_format_test "/home/zzp/code/NoPFS/pytorch/build/bin/memory_format_test")
add_test(cpu_rng_test "/home/zzp/code/NoPFS/pytorch/build/bin/cpu_rng_test")
add_test(ivalue_test "/home/zzp/code/NoPFS/pytorch/build/bin/ivalue_test")
add_test(vmap_test "/home/zzp/code/NoPFS/pytorch/build/bin/vmap_test")
add_test(type_test "/home/zzp/code/NoPFS/pytorch/build/bin/type_test")
add_test(tensor_interop_test "/home/zzp/code/NoPFS/pytorch/build/bin/tensor_interop_test")
add_test(List_test "/home/zzp/code/NoPFS/pytorch/build/bin/List_test")
add_test(TensorImpl_test "/home/zzp/code/NoPFS/pytorch/build/bin/TensorImpl_test")
add_test(KernelFunction_test "/home/zzp/code/NoPFS/pytorch/build/bin/KernelFunction_test")
add_test(kernel_function_legacy_test "/home/zzp/code/NoPFS/pytorch/build/bin/kernel_function_legacy_test")
add_test(kernel_function_test "/home/zzp/code/NoPFS/pytorch/build/bin/kernel_function_test")
add_test(kernel_lambda_legacy_test "/home/zzp/code/NoPFS/pytorch/build/bin/kernel_lambda_legacy_test")
add_test(kernel_lambda_test "/home/zzp/code/NoPFS/pytorch/build/bin/kernel_lambda_test")
add_test(kernel_stackbased_test "/home/zzp/code/NoPFS/pytorch/build/bin/kernel_stackbased_test")
add_test(make_boxed_from_unboxed_functor_test "/home/zzp/code/NoPFS/pytorch/build/bin/make_boxed_from_unboxed_functor_test")
add_test(CppSignature_test "/home/zzp/code/NoPFS/pytorch/build/bin/CppSignature_test")
add_test(backend_fallback_test "/home/zzp/code/NoPFS/pytorch/build/bin/backend_fallback_test")
add_test(op_allowlist_test "/home/zzp/code/NoPFS/pytorch/build/bin/op_allowlist_test")
add_test(op_registration_test "/home/zzp/code/NoPFS/pytorch/build/bin/op_registration_test")
add_test(blob_test "/home/zzp/code/NoPFS/pytorch/build/bin/blob_test")
add_test(common_test "/home/zzp/code/NoPFS/pytorch/build/bin/common_test")
add_test(context_test "/home/zzp/code/NoPFS/pytorch/build/bin/context_test")
add_test(event_test "/home/zzp/code/NoPFS/pytorch/build/bin/event_test")
add_test(graph_test "/home/zzp/code/NoPFS/pytorch/build/bin/graph_test")
add_test(init_test "/home/zzp/code/NoPFS/pytorch/build/bin/init_test")
add_test(module_test "/home/zzp/code/NoPFS/pytorch/build/bin/module_test")
add_test(net_async_tracing_test "/home/zzp/code/NoPFS/pytorch/build/bin/net_async_tracing_test")
add_test(net_dag_utils_test "/home/zzp/code/NoPFS/pytorch/build/bin/net_dag_utils_test")
add_test(net_simple_refcount_test "/home/zzp/code/NoPFS/pytorch/build/bin/net_simple_refcount_test")
add_test(net_test "/home/zzp/code/NoPFS/pytorch/build/bin/net_test")
add_test(observer_test "/home/zzp/code/NoPFS/pytorch/build/bin/observer_test")
add_test(operator_schema_test "/home/zzp/code/NoPFS/pytorch/build/bin/operator_schema_test")
add_test(operator_test "/home/zzp/code/NoPFS/pytorch/build/bin/operator_test")
add_test(parallel_net_test "/home/zzp/code/NoPFS/pytorch/build/bin/parallel_net_test")
add_test(plan_executor_test "/home/zzp/code/NoPFS/pytorch/build/bin/plan_executor_test")
add_test(serialization_test "/home/zzp/code/NoPFS/pytorch/build/bin/serialization_test")
add_test(stats_test "/home/zzp/code/NoPFS/pytorch/build/bin/stats_test")
add_test(timer_test "/home/zzp/code/NoPFS/pytorch/build/bin/timer_test")
add_test(transform_test "/home/zzp/code/NoPFS/pytorch/build/bin/transform_test")
add_test(workspace_test "/home/zzp/code/NoPFS/pytorch/build/bin/workspace_test")
add_test(inline_container_test "/home/zzp/code/NoPFS/pytorch/build/bin/inline_container_test")
add_test(fixed_divisor_test "/home/zzp/code/NoPFS/pytorch/build/bin/fixed_divisor_test")
add_test(math_test "/home/zzp/code/NoPFS/pytorch/build/bin/math_test")
add_test(fatal_signal_asan_no_sig_test "/home/zzp/code/NoPFS/pytorch/build/bin/fatal_signal_asan_no_sig_test")
add_test(simple_queue_test "/home/zzp/code/NoPFS/pytorch/build/bin/simple_queue_test")
add_test(proto_utils_test "/home/zzp/code/NoPFS/pytorch/build/bin/proto_utils_test")
add_test(cpuid_test "/home/zzp/code/NoPFS/pytorch/build/bin/cpuid_test")
add_test(smart_tensor_printer_test "/home/zzp/code/NoPFS/pytorch/build/bin/smart_tensor_printer_test")
add_test(cast_test "/home/zzp/code/NoPFS/pytorch/build/bin/cast_test")
add_test(predictor_test "/home/zzp/code/NoPFS/pytorch/build/bin/predictor_test")
add_test(data_filler_test "/home/zzp/code/NoPFS/pytorch/build/bin/data_filler_test")
add_test(AlgorithmsTest "/home/zzp/code/NoPFS/pytorch/build/bin/AlgorithmsTest")
add_test(BinaryMatchImplTest "/home/zzp/code/NoPFS/pytorch/build/bin/BinaryMatchImplTest")
add_test(GraphTest "/home/zzp/code/NoPFS/pytorch/build/bin/GraphTest")
add_test(MatchTest "/home/zzp/code/NoPFS/pytorch/build/bin/MatchTest")
add_test(NeuralNetTest "/home/zzp/code/NoPFS/pytorch/build/bin/NeuralNetTest")
add_test(SubgraphMatcherTest "/home/zzp/code/NoPFS/pytorch/build/bin/SubgraphMatcherTest")
add_test(TarjansImplTest "/home/zzp/code/NoPFS/pytorch/build/bin/TarjansImplTest")
add_test(TopoSortTest "/home/zzp/code/NoPFS/pytorch/build/bin/TopoSortTest")
add_test(mpi_test "/home/zzp/code/NoPFS/pytorch/build/bin/mpi_test")
add_test(time_observer_test "/home/zzp/code/NoPFS/pytorch/build/bin/time_observer_test")
add_test(ssa_test "/home/zzp/code/NoPFS/pytorch/build/bin/ssa_test")
add_test(batch_matmul_op_test "/home/zzp/code/NoPFS/pytorch/build/bin/batch_matmul_op_test")
add_test(boolean_unmask_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/boolean_unmask_ops_test")
add_test(conv_transpose_op_mobile_test "/home/zzp/code/NoPFS/pytorch/build/bin/conv_transpose_op_mobile_test")
add_test(elementwise_op_test "/home/zzp/code/NoPFS/pytorch/build/bin/elementwise_op_test")
add_test(generate_proposals_op_test "/home/zzp/code/NoPFS/pytorch/build/bin/generate_proposals_op_test")
add_test(generate_proposals_op_util_boxes_test "/home/zzp/code/NoPFS/pytorch/build/bin/generate_proposals_op_util_boxes_test")
add_test(generate_proposals_op_util_nms_test "/home/zzp/code/NoPFS/pytorch/build/bin/generate_proposals_op_util_nms_test")
add_test(half_float_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/half_float_ops_test")
add_test(string_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/string_ops_test")
add_test(text_file_reader_utils_test "/home/zzp/code/NoPFS/pytorch/build/bin/text_file_reader_utils_test")
add_test(utility_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/utility_ops_test")
add_test(int8_test "/home/zzp/code/NoPFS/pytorch/build/bin/int8_test")
add_test(int8_roi_align_op_test "/home/zzp/code/NoPFS/pytorch/build/bin/int8_roi_align_op_test")
add_test(backend_cutting_test "/home/zzp/code/NoPFS/pytorch/build/bin/backend_cutting_test")
add_test(bound_shape_inference_test "/home/zzp/code/NoPFS/pytorch/build/bin/bound_shape_inference_test")
add_test(converter_nomigraph_test "/home/zzp/code/NoPFS/pytorch/build/bin/converter_nomigraph_test")
add_test(dead_code_elim_test "/home/zzp/code/NoPFS/pytorch/build/bin/dead_code_elim_test")
add_test(device_test "/home/zzp/code/NoPFS/pytorch/build/bin/device_test")
add_test(distributed_test "/home/zzp/code/NoPFS/pytorch/build/bin/distributed_test")
add_test(mobile_test "/home/zzp/code/NoPFS/pytorch/build/bin/mobile_test")
add_test(split_slss_test "/home/zzp/code/NoPFS/pytorch/build/bin/split_slss_test")
add_test(nnpack_test "/home/zzp/code/NoPFS/pytorch/build/bin/nnpack_test")
add_test(depthwise3x3_conv_op_test "/home/zzp/code/NoPFS/pytorch/build/bin/depthwise3x3_conv_op_test")
add_test(common_subexpression_elimination_test "/home/zzp/code/NoPFS/pytorch/build/bin/common_subexpression_elimination_test")
add_test(conv_to_nnpack_transform_test "/home/zzp/code/NoPFS/pytorch/build/bin/conv_to_nnpack_transform_test")
add_test(pattern_net_transform_test "/home/zzp/code/NoPFS/pytorch/build/bin/pattern_net_transform_test")
add_test(cuda_atomic_ops_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_atomic_ops_test")
add_test(cuda_complex_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_complex_test")
add_test(cuda_complex_math_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_complex_math_test")
add_test(cuda_integer_divider_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_integer_divider_test")
add_test(cuda_apply_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_apply_test")
add_test(cuda_stream_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_stream_test")
add_test(cuda_half_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_half_test")
add_test(cuda_distributions_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_distributions_test")
add_test(cuda_optional_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_optional_test")
add_test(cuda_packedtensoraccessor_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_packedtensoraccessor_test")
add_test(cuda_reportMemoryUsage_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_reportMemoryUsage_test")
add_test(cuda_vectorized_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_vectorized_test")
add_test(cuda_dlconvertor_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_dlconvertor_test")
add_test(cuda_generator_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_generator_test")
add_test(cuda_cub_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_cub_test")
add_test(cuda_cudnn_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_cudnn_test")
add_test(cuda_tensor_interop_test "/home/zzp/code/NoPFS/pytorch/build/bin/cuda_tensor_interop_test")
add_test(blob_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/blob_gpu_test")
add_test(context_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/context_gpu_test")
add_test(event_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/event_gpu_test")
add_test(net_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/net_gpu_test")
add_test(operator_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/operator_gpu_test")
add_test(math_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/math_gpu_test")
add_test(mpi_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/mpi_gpu_test")
add_test(conv_op_cache_cudnn_test "/home/zzp/code/NoPFS/pytorch/build/bin/conv_op_cache_cudnn_test")
add_test(batch_matmul_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/batch_matmul_op_gpu_test")
add_test(batch_permutation_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/batch_permutation_op_gpu_test")
add_test(elementwise_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/elementwise_op_gpu_test")
add_test(generate_proposals_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/generate_proposals_op_gpu_test")
add_test(generate_proposals_op_util_nms_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/generate_proposals_op_util_nms_gpu_test")
add_test(operator_fallback_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/operator_fallback_gpu_test")
add_test(reshape_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/reshape_op_gpu_test")
add_test(roi_align_op_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/roi_align_op_gpu_test")
add_test(utility_ops_gpu_test "/home/zzp/code/NoPFS/pytorch/build/bin/utility_ops_gpu_test")
subdirs("aten")
subdirs("core")
subdirs("serialize")
subdirs("utils")
subdirs("perfkernels")
subdirs("contrib")
subdirs("predictor")
subdirs("predictor/emulator")
subdirs("core/nomnigraph")
subdirs("db")
subdirs("distributed")
subdirs("ideep")
subdirs("image")
subdirs("video")
subdirs("mobile")
subdirs("mpi")
subdirs("observers")
subdirs("onnx")
subdirs("operators")
subdirs("operators/rnn")
subdirs("quantization/server")
subdirs("operators/quantized")
subdirs("opt")
subdirs("proto")
subdirs("python")
subdirs("queue")
subdirs("sgd")
subdirs("share")
subdirs("transforms")
subdirs("../test_jit")
subdirs("../test_tensorexpr")
subdirs("../test_cpp_c10d")
subdirs("../dist_autograd")
subdirs("../test_cpp_rpc")
subdirs("../test_api")
subdirs("../test_mobile_nnc")
subdirs("torch")
