# CMake generated Testfile for 
# Source directory: /home/zzp/code/NoPFS/pytorch/c10/test
# Build directory: /home/zzp/code/NoPFS/pytorch/build/c10/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c10_CompileTimeFunctionPointer_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_CompileTimeFunctionPointer_test")
add_test(c10_DeviceGuard_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_DeviceGuard_test")
add_test(c10_Device_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_Device_test")
add_test(c10_DispatchKeySet_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_DispatchKeySet_test")
add_test(c10_StreamGuard_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_StreamGuard_test")
add_test(c10_InlineDeviceGuard_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_InlineDeviceGuard_test")
add_test(c10_InlineStreamGuard_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_InlineStreamGuard_test")
add_test(c10_SizesAndStrides_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_SizesAndStrides_test")
add_test(c10_Array_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_Array_test")
add_test(c10_Bitset_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_Bitset_test")
add_test(c10_C++17_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_C++17_test")
add_test(c10_ConstexprCrc_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_ConstexprCrc_test")
add_test(c10_Half_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_Half_test")
add_test(c10_LeftRight_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_LeftRight_test")
add_test(c10_Metaprogramming_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_Metaprogramming_test")
add_test(c10_ThreadLocal_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_ThreadLocal_test")
add_test(c10_TypeIndex_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_TypeIndex_test")
add_test(c10_TypeList_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_TypeList_test")
add_test(c10_TypeTraits_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_TypeTraits_test")
add_test(c10_accumulate_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_accumulate_test")
add_test(c10_bfloat16_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_bfloat16_test")
add_test(c10_complex_math_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_complex_math_test")
add_test(c10_complex_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_complex_test")
add_test(c10_either_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_either_test")
add_test(c10_exception_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_exception_test")
add_test(c10_flags_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_flags_test")
add_test(c10_intrusive_ptr_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_intrusive_ptr_test")
add_test(c10_irange_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_irange_test")
add_test(c10_logging_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_logging_test")
add_test(c10_optional_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_optional_test")
add_test(c10_ordered_preserving_dict_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_ordered_preserving_dict_test")
add_test(c10_registry_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_registry_test")
add_test(c10_string_view_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_string_view_test")
add_test(c10_tempfile_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_tempfile_test")
add_test(c10_typeid_test "/home/zzp/code/NoPFS/pytorch/build/bin/c10_typeid_test")
